# Generated by Django 4.1.3 on 2022-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='IMDb_Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Meta_Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Plot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Rott_Rating',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
