# Generated by Django 4.1.3 on 2022-11-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_favorite_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='ido',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='watched',
            name='ido',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='ido',
            field=models.IntegerField(null=True),
        ),
    ]
