# Generated by Django 4.1.3 on 2022-11-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_favorite_ido_watched_ido_wishlist_ido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ido', models.IntegerField()),
                ('Title', models.CharField(max_length=255)),
                ('Rating', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=255)),
                ('IMDb_Rating', models.CharField(max_length=255)),
                ('Rott_Rating', models.CharField(max_length=255)),
                ('Meta_Rating', models.CharField(max_length=255)),
                ('Cast', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('Plot', models.CharField(max_length=255)),
            ],
        ),
    ]
