# Generated by Django 4.1.3 on 2022-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='ido',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='ido',
            field=models.IntegerField(null=True),
        ),
    ]
