# Generated by Django 4.1.3 on 2022-11-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_members_ido_alter_searched_ido'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='User',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watched',
            name='User',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='User',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
