# Generated by Django 4.1.3 on 2022-11-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_favorite_user_watched_user_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='Genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searched',
            name='Genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watched',
            name='Genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Genre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
