# Generated by Django 4.1.3 on 2022-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_favorite_genre_members_genre_searched_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='Cast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='Year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Cast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Cast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='IMDb_Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Meta_Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Plot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Rott_Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searched',
            name='Year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='Cast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='Year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='Cast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='Rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='Year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
