# Generated by Django 4.1.3 on 2022-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_favorite_similar_members_similar_searched_similar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searched',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watched',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
